from github import Github
import os

def create_fix_pr(repo_full_name: str,
                  file_path: str,
                  updated_code: str,
                  token: str,
                  title: str = "AI‑generated code fix",
                  base_branch: str = "main") -> str:
    gh = Github(token)
    repo = gh.get_repo(repo_full_name)
    # create a new branch from main
    source = repo.get_branch(base_branch)
    branch_name = f"ai-fix-{int(time.time())}"
    repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=source.commit.sha)
    # commit updated file
    repo.update_file(path=file_path,
                     message=title,
                     content=updated_code,
                     branch=branch_name)
    # open PR
    pr = repo.create_pull(title=title,
                          body="Automated fix generated by AI.",
                          head=branch_name,
                          base=base_branch)
    return pr.html_url
